# Q1

In [ ]:
import numpy as np 
import scipy.integrate as sc
import matplotlib.pyplot as plt

# Value of initial condition
y0 = 1

# Differential equation 
def dydt(y, t):
    # Define your differential equation here
    # For example, let's use a simple one: dy/dt = -y
    return -y

# Create the x axis for the integration
# Time to response is 2 minutes
start = 0
end = 2
t = np.linspace(start, end, 100)  # You need to specify the number of points (e.g., 100)

# Integration of the differential equation
P = sc.odeint(dydt, y0, t)

# Plotting the results for the initial value
plt.figure()
plt.plot(t, P)
plt.xlabel('Time')
plt.ylabel('Function')
plt.title('Function vs Time')
plt.show()


# Q2

In [7]:
# Import necessary libraries
import numpy as np
import scipy as sc



In [8]:

# Define the coefficient matrix A
A = np.array([[2, 4, 6], [5, 3, 2], [7, 8, 9]])
print(A)

[[2 4 6]
 [5 3 2]
 [7 8 9]]


In [9]:
# Define the right-hand side vector b
b = np.array([[18], [13], [30]])
print(b)

[[18]
 [13]
 [30]]


In [10]:
# calculate the inverse of A and multiply by b to find the solution vector 
C = sc.linalg.inv(A).dot(b)
print(C) 

[[ 4.5]
 [-7.5]
 [ 6.5]]


In [11]:
# Alternatively, use the solve funvtion to find the solution vector directly
D = sc.linalg.solve(A, b)
print (D)

[[ 4.5]
 [-7.5]
 [ 6.5]]


# Q3

In [ ]:
import requests
import matplotlib.pyplot as plt

def get_weather_data(latitude, longitude, forecast_days):
    url = f"https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}&hourly=temperature_2m&timezone=Asia%2FSingapore&forecast_days={forecast_days}.json"
    response = requests.get(url)
    data = response.json()
    return data

def plot_temperature_trend(data, latitude, longitude, forecast_days):
    hourly_data = data['hourly']['temperature_2m']
    time_points = [entry['timestamp'] for entry in hourly_data]
    temperatures = [entry['value'] for entry in hourly_data]

    plt.figure()
    plt.plot(time_points, temperatures, label='Temperature Trend', marker='o')
    plt.xlabel('Time')
    plt.ylabel('Temperature (°C)')
    plt.title(f'Temperature Trend for {forecast_days} Days\nLocation: {latitude}, {longitude}')
    plt.grid(True)
    plt.legend()
    plt.show()

def main():
    latitude = 2.375  # Replace with your preferred latitude
    longitude = 112.5  # Replace with your preferred longitude

    while True:
        try:
            forecast_days = int(input("Enter the number of forecast days (1-16): "))
            if 1 <= forecast_days <= 16:
                break
            else:
                print("Please enter a number between 1 and 16.")
        except ValueError:
            print("Invalid input. Please enter a valid number.")

    data = get_weather_data(latitude, longitude, forecast_days)
    plot_temperature_trend(data, latitude, longitude, forecast_days)

if __name__ == "__main__":
    main()
